### ISSUE TITLE
Error: Cannot find the Related documents when execute `poetry run generate` 

### ISSUE THREAD

**Issue by faynef** [Azure-Samples/llama-index-python#12]
**Describe the issue:**
Running `poetry run generate` reports an error: Poetry could not find a `pyproject.toml`.
![image](https://github.com/user-attachments/assets/6fbf7b34-30bf-4d44-bf9d-fb7e1d6d54ac)

**Repro Steps:**

1. `azd init --template llama-index-python`
2. `azd auth login`
3. Create a python virtual environment and install the python dependencies:
    ```
    cd backend
    python3 -m venv venv
    source venv/bin/activate
    poetry install```
4. Install the frontend dependencies:
   ```
   cd ..
   cd frontend
   npm install```
5. `azd up`
6. `azd env get-values > .env`
7. `poetry run generate`

**Environment:**
- azd version: 1.9.5 (commit cd2b7af9995d358aab33c782614f801ac1997dde)
- OS: Windows11

**Suggestions:**
Refer to the `dev container` test steps in the [readme](https://github.com/Azure-Samples/llama-index-python?tab=readme-ov-file#vs-code-dev-containers). It is recommended to put `poetry run generate` before step 4.

**Expected Behavior:**
`poetry run generate` runs successfully .

@marlenezw and @hemarina for notification.

**Comment by marlenezw** [comment]
This error was caused by moving into the frontend directory which doesn't have poetry in it. I've updated the Readme in the PR mentioned
