### ISSUE TITLE
Command error in `azure.yaml`

### ISSUE THREAD

**Issue by faynef** [Azure-Samples/llama-index-python#13]
**Describe the issue:**
Command errors in the `azure.yaml` file caused errors when running `azd up`.
![image](https://github.com/user-attachments/assets/e7f27f60-5da7-4174-acef-467dc2facf89)

**Repro Steps:**
1. `azd init --template llama-index-python`
2. `azd auth login`
3. `azd up`

**Environment:**

- azd version: 1.9.5 (commit cd2b7af9995d358aab33c782614f801ac1997dde)
- OS: Windows11, codespace, dev containers

**Expected Behavior:**
`azd up` runs successfully.

@marlenezw and @hemarina for notification.

**Comment by marlenezw** [comment]
Thanks for this issue @faynef, I've just merged a fix in the PR mentioned above.
