### ISSUE TITLE
Error: Pipeline issues when execute `azd pipeline config` .

### ISSUE THREAD

**Issue by faynef** [Azure-Samples/llama-index-python#15]
**Describe the issue:**
Running `azd pipeline config` reports errors, as follows:
![image](https://github.com/user-attachments/assets/71c17161-45ed-4488-834f-3309a7438dbc)

- Configure Azure Developer Pipeline: Build and test - jobs: ubuntu and macos latest /Node.js v20 

![image](https://github.com/user-attachments/assets/bb0f6a7b-326d-4c25-a1b4-44f0dac7eb88)

- Configure Azure Developer Pipeline: Build and test - jobs: windows latest /Node.js v20

![image](https://github.com/user-attachments/assets/d0bd6d69-8a72-455b-9bfe-6511026a7c08)

- Configure Azure Developer Pipeline: Build and test - jobs:  build_test_all

![image](https://github.com/user-attachments/assets/d17ce145-28a7-4f82-be92-0f64f47d117c)

- Configure Azure Developer Pipeline: Deploy to Azure

![image](https://github.com/user-attachments/assets/050c8f2b-e7eb-4b9d-a86e-9b814f076fea)

**Repro Steps:**
1. `azd init --template llama-index-python`
2. `azd auth login`
3. `azd pipeline config`

**Environment:**
- azd version: 1.9.5 (commit cd2b7af9995d358aab33c782614f801ac1997dde)
- OS: Windows11, Dev containers, Codespace

**Expected Behavior:**
`azd pipeline config` runs successfully.

@marlenezw and @hemarina for notification.

**Comment by marlenezw** [comment]
Github actions is now working as expected with pipeline config
